### ISSUE TITLE
Add feature

### ISSUE THREAD

**Issue by toinfinityandbeyonddd** [DamagingRose/Rose-RAT#2]
Can you add download file from shell?

**Comment by xpierroz** [comment]
what do you mean by that, that the attacker sends a file and the victims download it and runs it?

**Comment by vannhoanganhh** [comment]
No, i mean the execute shell. Can i put a command download file from victim?

**Comment by xpierroz** [comment]
you mean that the attackers received a file from the victim's pc?

**Comment by xpierroz** [comment]
waiting for a reply, or i will close this

**Comment by vannhoanganhh** [comment]
> 

Yes

**Comment by vannhoanganhh** [comment]
> you mean that the attackers received a file from the victim's pc?

I mean that
